name: cyclon
description: Cyclon project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.12.2
  shared_preferences: ^2.0.6
  tuple: ^2.0.0
  encrypt: ^4.0.0
  cupertino_icons: ^1.0.2
  geolocator: ^7.1.0
  geolocator_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.0.0
  introduction_screen: ^2.1.0
  flutter_facebook_auth: ^3.5.0
  google_sign_in: ^5.0.5
  socket_io_client: ^0.9.12
  flutter_local_notifications: ^8.1.1
  font_awesome_flutter: ^9.1.0
  webview_flutter: ^2.0.10
  url_launcher: ^6.0.9
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  generate: true
  uses-material-design: true
  assets:
    - assets/_404_en.png
    - assets/_404_es.png
    - assets/config.png
    - assets/cyclon_mini.png
    - assets/facebook.png
    - assets/facebook_reverse.png
    - assets/favicon.ico
    - assets/google.png
    - assets/map.png
    - assets/twitter.png
    - assets/mobile.png
    - assets/alert.png
    - assets/social_media.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages