type User{
	name: String
	lastName: String
	email: String
	location: Geolocation
	password: String
	type: Int,
	verify: Boolean
}

type Cyclone{
	name: String
	appearance: String
	lastUpdate: String
	origin: Geolocation
	predictedTrajectory: [Trajectory]
	realTrajectory: [Trajectory]
	active: Boolean
	category: String
}

type RiskArea{
	position: Geolocation
	ocean: String
	date:  String
}

type Trajectory{
   position: Geolocation
	windSpeed: Float
	hurrSpeed: Float
	temperature: Float
	pressure: Float
	date: String
}

type Geolocation{
	lat: Float
	lng: Float
}

type Query {
    activeCyclones: [Cyclone]
	searchCyclone (year: Int): [Cyclone]
}